name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - sync-labels.yml
      - labels.yml
jobs:
  sync-labels:
    name: sync-labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Sync labels
        uses: Brightspace/third-party-actions@micnncim/action-label-syncer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels.yml
