name: build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Read configs
        id: configs
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{ steps.configs.outputs.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: npm i
      - name: Run tests
        if: (!startsWith(github.ref, 'refs/tags/')) # run on all but tags
        run: npm run test:polymer:sauce
        env:
          SAUCE_USERNAME: lweber-d2l
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_LABS_ACCESS_KEY }}
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/') # run on only tags
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
