name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Incremental Release
        id: incremental-release
        uses: BrightspaceUI/actions/incremental-release@master
        with:
          DEFAULT_INCREMENT: patch
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
